ChristianMurphy/nicest

CONTRIBUTING.md
lib/server.js
modules/shared-template/default.jade
modules/welcome/view/welcome.jade

Correctly resolves relative path to jade files.
Also Assessment is no longer an internal component, all internal references have been removed.

Vision Fix

---

modules/github-individual-project/view/choose-repository.jade
modules/github-individual-project/view/choose-students.jade
modules/github-individual-project/view/confirm.jade
modules/github/view/login.jade
modules/user/view/handler.js
modules/user/view/list.jade
modules/user/view/view.jade

resolves #17 
resolves #19 
resolves #20 
resolves #21

Plugin polish

---

lib/server.js

Documentation Fix

---

lib/server.js
package.json

Content Security Policy

---

lib/server.js
modules/github-individual-project/view/route.js
modules/shared-template/default.jade
modules/welcome/view/route.js

allow fonts to be correctly displayed.
add character encoding to shared template.
allow jquery, max cdn oss and inline scripts for animated pages.

CSP fixes for Animations

---

modules/user/view/handler.js
modules/user/view/view.jade

Fixes to User Plugin

---

.eslintrc
modules/team/model/team.js
modules/team/view/handler.js
modules/team/view/list.jade
modules/team/view/route.js
modules/team/view/view.jade
modules/user/model/user.js

resolves #18 
needed for #3 and #11

Team Plugin UI

---

lib/server.js

API Page fix

---

lib/server.js
modules/github-individual-project/view/choose-repository.jade
modules/github-individual-project/view/choose-students.jade
modules/shared-template/default.jade
modules/team/view/view.jade
modules/welcome/view/welcome.jade

Semantic UI Library updated to 2.1.2 [changes](http://semantic-ui.com/introduction/new.html)

Update Semantic UI

---

.eslintrc
bin/cli.js
lib/server.js
modules/code-project/plugin.js
modules/code-project/tasks/create-github-repositories.js
modules/code-project/view/handler.js
modules/documentation/plugin.js
modules/github/plugin.js
modules/recipe/plugin.js
modules/team/plugin.js
modules/user/plugin.js
modules/welcome/plugin.js
package.json

add new rules:
- `global-require`
- `space-before-keywords`
- `require-jsdoc`
removes rule:
- `prefer-arrow-callback`
resolves some issues with Module loading at top level of plugins

ESLint 1.4.1

---

modules/code-project/tasks/seed-git-repositories.js

Git Credentials on Clone

---

bin/cli.js
lib/server.js

adds a cli option to set secret token
resolves #64

CLI token option

---

modules/code-project/tasks/gather-github-users.js
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/code-project/view/handler.js

resolves #61 
resolves #63 
resolves #72

Rework User/Team Session Management

---

modules/code-project/view/choose-students.jade
modules/code-project/view/handler.js
modules/code-project/view/route.js

Use query to prevent caching issue when toggling

---

modules/code-project/view/choose-issue-tracker.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/code-project/view/handler.js
modules/code-project/view/route.js

choose students is first step

---

modules/import-export/task/import.js
modules/import-export/view/handler.js
modules/import-export/view/import.jade

Import success message

---

modules/code-project/view/choose-students.jade

Suggest creating users and teams if none exist

---

modules/code-project/task/gather-github-users.js
modules/code-project/view/choose-students.jade

Allow Special Characters

---

modules/code-project/view/error.jade
modules/code-project/view/handler.js
modules/code-project/view/route.js
modules/code-project/view/success.jade

Success and Error pages for Code Project

---

modules/code-project/view/choose-issue-tracker.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/route.js
package.json

Issue Tracker - Only require name when enabled

---

lib/server.js
modules/code-project/view/handler.js

Store errors into request log (better for server debugging).

Code Project - Better Error Logging

---

.travis.yml
README.md
bin/cli.js
lib/server.js
package.json

Set Github App Token

---

modules/welcome/view/route.js

No more Github login to simply see the welcome page.

Welcome can be accessed as Guest

---

lib/server.js

Add prefix so that recipe routes are ignored when prefix is enabled

Update documentation filter

---

modules/code-project/task/configure-ca-dashboard.js
modules/code-project/task/gather-ca-users.js
modules/code-project/view/choose-assessment-system.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/code-project/view/handler.js
modules/code-project/view/route.js

CA Dashboard Setup

---

modules/code-project/view/choose-assessment-system.jade

per conversation with @kgary using `swent0linux.asu.edu/ca_dashboard` as default server url

Default Assessment Step to point the swent

---

README.md
modules/user/api/route.js
modules/user/model/user.js
modules/user/view/handler.js
modules/user/view/route.js
modules/user/view/view.jade

Adds admin option to the User view

Admin user view

---

.eslintrc
lib/server.js
modules/code-project/task/create-taiga-boards.js
modules/code-project/task/gather-ca-users.js
modules/code-project/task/gather-github-users.js
modules/code-project/view/handler.js
modules/github/view/handler.js
modules/import-export/task/import.js
modules/import-export/view/handler.js
modules/recipe/model/recipe.js
modules/team/view/handler.js
modules/user/view/handler.js

***ALERT***
The issue with running code project on multiple users or teams is back.
Avoid doing this an current code.
**Commit Overview**
* Move risky code to end, so crash will have less effect.
**TODO**
* Seed each repo on at a time instead of in parallel

Reduce Errors Seeding Multiple Repos

---

modules/code-project/view/choose-issue-tracker.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/code-project/view/handler.js

temporary measure for FIE demo

Hide Assessment Step

---

.gitignore
README.md
bin/cli.js
lib/database.js
lib/server.js
package.json
tasks/.eslintrc
tasks/dev.js
tasks/doc.js
tasks/helpers/read-promise.js
tasks/helpers/start-server.js
tasks/helpers/write-file-promise.js
tasks/init.js
tasks/lint.js
tasks/start.js
tasks/stop.js

**Commit Overview**
* Completely reworked configuration
- now based on a persistent json file
- previously was completely command line arguements
* Completely rework CLI and setup flow
- Setup is now managed by `nicest init`
- Starting and stopping production server now managed by `nicest start` and `nicest stop`
- Additional `dev`, `doc` and `lint` commands
resolves #128 
resolves #126

nicest.json

---

modules/code-project/view/choose-issue-tracker.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/code-project/view/handler.js

Reverts ChristianMurphy/nicest#159
Merge after FIE demo

Show Assessment Step

---

tasks/admin.js
tasks/doc.js
tasks/init.js

Fixing some spelling and grammar mistakes in the CLI.

Better CLI Wording

---

tasks/init.js

Secret Token Fix

---

modules/code-project/task/configure-ca-dashboard.js
modules/code-project/view/choose-assessment-system.jade

* Assessment tool only accepts a single project at a time
* Update default url for assessment tool.

Assessment Fix

---

.eslintrc
bin/cli.js
lib/database.js
lib/server.js
modules/code-project/task/configure-ca-dashboard.js
modules/code-project/task/create-github-repositories.js
modules/code-project/task/create-taiga-boards.js
modules/code-project/task/gather-ca-users.js
modules/code-project/task/gather-github-users.js
modules/code-project/task/seed-git-repositories.js
modules/code-project/view/handler.js
modules/github/view/handler.js
modules/import-export/task/import.js
modules/import-export/view/handler.js
modules/team/api/handler.js
modules/team/view/handler.js
modules/user/api/handler.js
modules/user/view/handler.js
tasks/admin.js
tasks/doc.js
tasks/helpers/read-promise.js
tasks/helpers/start-server.js
tasks/helpers/write-file-promise.js
tasks/init.js
tasks/lint.js
tasks/start.js
tasks/stop.js

making the leap to ES6 arrow functions for callbacks

Arrow Function Callbacks

---

modules/code-project/view/choose-assessment-system.jade
modules/code-project/view/choose-issue-tracker.jade
modules/code-project/view/choose-repository.jade
modules/code-project/view/choose-students.jade
modules/code-project/view/confirm.jade
modules/shared-template/default.jade
modules/team/view/view.jade
modules/user/view/view.jade
modules/welcome/view/welcome.jade

See https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.1.5 for changes

Semantic UI 2.1.5

---

modules/code-project/task/configure-ca-dashboard.js

add JSDoc to the CA Dashboard configuration code

CA Dashboard Integration Documentation

---

.eslintrc
package.json

add new lodash rules
alphabetize eslint lodash rules

Update ESLint Lodash plugin

---

modules/code-project/task/create-taiga-boards.js
modules/code-project/task/gather-ca-users.js
modules/code-project/task/gather-github-users.js
modules/import-export/task/import.js
modules/team/model/team.js
modules/user/model/user.js

Document Promise Resolution

---

modules/code-project/view/handler.js
modules/team/api/handler.js
modules/user/api/handler.js
tasks/admin.js
tasks/init.js

Checks for exceptions.
IMO has better readability then two parameters in `.then()`

Promise Catch

---

README.md
bin/cli.js
lib/server.js
modules/user/api/route.js
modules/user/model/user.js
modules/user/view/handler.js
modules/user/view/route.js
modules/user/view/view.jade
tasks/user.js

Updated and more flexible user roles.

User Roles

---

modules/user/model/user.js

When no user role is specified default role to `student`

Default User Role

---

.eslintrc.yml

Remove ESLint exceptions for `_`

Remove Lodash Lint Exceptions

---

.remarkrc
.travis.yml
CONTRIBUTING.md
README.md
package.json
tasks/helpers/start-server.js
tasks/init.js
tasks/start.js
tasks/stop.js
tasks/user.js

* add `remark-lint` as a markdown validator
* add prefix to server start print out
* load only needed dependencies for nicest CLI

Remark Lint

---

.pug-lint.json
package.json

Update Pug Lint and Remark

---

lib/server.js
modules/code-project/view/handler.js
modules/github/view/handler.js
package.json

Update API calls to adjust for breaking changes.

Update Yar and Auth Cookie

---

README.md
modules/code-project/README.md

Code Project README

---

modules/code-project/route.js

Fix for Course selection

---

modules/code-project/task/configure-ca-dashboard.js
modules/code-project/task/gather-ca-users.js

sends both instructor name and email to CAssess

CAssess - Add instructor email

---

modules/code-project/view/choose-issue-tracker.jade

better wording for taiga toggle

---

modules/import-export/task/import-courses.js
modules/import-export/xml/schema.xsd

update schema to check ids as key references

---

modules/import-export/xml/schema.xsd

Import - Validate username and email

---

modules/code-project/handler/confirm.js
modules/code-project/task/seed-git-repositories.js

I have tested it with up to 10 at a time.
@kgary it's finally fixed

Nicest can now seed an arbitrary number of repos

---

modules/code-project/view/choose-students.jade

Consistent Assessment Icon

---

modules/course/route.js
modules/import-export/xml/schema.xsd
modules/team/api/route.js
modules/team/route.js
modules/user/api/route.js
modules/user/route.js

add start and end anchors to as many regex as possible
improved email validation

Improved Regex

---

modules/course/route.js
modules/team/route.js

allow numbers and hyphens in team and course names

---

modules/code-project/handler/choose-repository.js
modules/github/handler/list.js

Github Fetch All Repos

---

.eslintrc.yml
modules/github/handler/login-view.js
modules/import-export/handler/download-xml.js
modules/recipe/model/recipe.js
package.json

update node modules

---

package.json

include only necessary code in package

Reduce Package Size

---

modules/code-project/view/choose-assessment-system.pug
modules/code-project/view/choose-course.pug
modules/code-project/view/choose-issue-tracker.pug
modules/code-project/view/choose-repository.pug
modules/code-project/view/choose-students.pug
modules/code-project/view/confirm.pug
modules/course/view/list.pug
modules/course/view/view.pug
modules/team/view/view.pug
modules/user/view/view.pug
modules/welcome/view/welcome.pug

No Default Repository

---

Dockerfile
docker-compose.yml
lib/server.js
modules/code-project/task/create-taiga-boards.js
modules/code-project/task/gather-ca-users.js
modules/code-project/task/gather-github-users.js
modules/code-project/task/seed-git-repositories.js
modules/course/handler/remove.js
modules/course/handler/save.js
modules/course/handler/view-empty.js
modules/course/handler/view.js
modules/import-export/task/import-courses.js
modules/import-export/task/import-users.js
package.json
tasks/init.js
tasks/user.js

Docker Compose Setup

---

README.md

Note required versions

---

package-lock.json
package.json

fix(package): update chalk to version 2.0.1

---

package.json

fix(package): update boom to version 7.1.1

---

package.json

fix(package): update vision to version 5.1.0

---

modules/code-project/task/configure-ca-dashboard.js

The changes for posting (/POST) the provisioned data (team and project) to CASSESS .

/POST to CASSESS
